### PR TITLE
Pull request for code review

### PR DESCRIPTION
**Pull request by ahmadchata**
# Project: Using Bootstrap
- This project is a replica of the news site Newsweek.com using the Bootstrap framework.
- Use Bootstrap classes wherever possible.
- Make sure the page doesn't break on small screens.

### CODE REVIEW

**Comment by christianotieno** [comment]
## Pull Request under review by Christian Otieno (TSE)

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @ahmadchata  :wave:
-
You have done a splendid job! :tada: Everything looks great. Keep it up.
We, however, do have some subtle changes to carry out before we proceed (see review comment).
##
- The [clone](https://raw.githack.com/ahmadchata/newsweek/feature-homepage/index.html) shows good understanding and usage of bootstrap 💯. Kindly note that for this project, we have to make sure nothing is messed up.
- Compare the differences below and work on the suggested changes. 👇 

### Navbar

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://raw.githack.com/ahmadchata/newsweek/feature-homepage/index.html)|
|:---:|:---:|
|source|clone|

- [x] Ensure the navbar is the same width as the main content.
### Footer

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://raw.githack.com/ahmadchata/newsweek/feature-homepage/index.html)|
|:---:|:---:|
|footer|footer-clone|

- [x] Ensure that the footer is the same width as the main content.

- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by ahmadchata** [comment]
# Changes Made
- Made navbar same width as the main content.
- Made footer same width as the main content.

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work, @ahmadchata! 🖥️ 👀 ✨ 
## However, some changes are still required... 🧰 🔨 🔧 

- On medium display, the Subscribe and Newsletter sections are supposed to be the same width. However, on your version, the Subscribe section is slightly less wide than the Newsletter section. Please fix this.

| **Your version** | **Original page** |
|---|---|
| image | image |

### Submit these changes and request a new code review! 😄 👍 
### Questions of comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Comment by ahmadchata** [comment]
# Changes Made
- Fix the width of the subscribe and newsletter section on medium screens.

**Review by voscarmv — APPROVED** [review]
# Nice work, @ahmadchata 👍 
## It's a ✔️ Yes ✔️ for me! Congratulations, you're project's been approved 🥳 🎉 

**[OPTIONAL]** Please remember to update the Live Demo link on your `README.md` file! Potential employers might be wacthing 👀 And you definitely want them to be able to look at your finished work!

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Pull request merged**
